// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderFlow.Infra.Data;

#nullable disable

namespace OrderFlow.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250930211136_UpdatePedidoFK")]
    partial class UpdatePedidoFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderFlow.Domain.Entities.Ocorrencia", b =>
                {
                    b.Property<int>("IdOcorrencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOcorrencia"));

                    b.Property<DateTime>("HoraOcorrencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IndFinalizadora")
                        .HasColumnType("boolean");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoOcorrencia")
                        .HasColumnType("integer");

                    b.HasKey("IdOcorrencia");

                    b.HasIndex("PedidoId");

                    b.ToTable("Ocorrencias");
                });

            modelBuilder.Entity("OrderFlow.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("NumeroPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumeroPedido"));

                    b.Property<DateTime>("HoraPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPedido")
                        .HasColumnType("integer");

                    b.Property<bool>("IndEntregue")
                        .HasColumnType("boolean");

                    b.HasKey("NumeroPedido");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("OrderFlow.Domain.Entities.Ocorrencia", b =>
                {
                    b.HasOne("OrderFlow.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("OrderFlow.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Ocorrencias");
                });
#pragma warning restore 612, 618
        }
    }
}
